Repository ProvidenceGeeks/website-frontend, pull requests merged in 2019-10, with the labels that each got.

#186 Fix #152: Use `font-display` property to render fallback font
  src/components/bootstrap/bootstrap.scss
Labels: enhancement

#184 Fix #112, Fix #125, Fix #127, Fix #150: Resolve layout overflow
  src/components/hero-banner/hero-banner.scss
  src/components/share-bar/share-bar.jsx
  src/components/share-bar/share-bar.scss
  src/views/post-details/post-details.scss
Labels: P1, blog, bug

#185 Fix #111: display images without page scroll
  src/components/card/card.jsx
Labels: P1, blog, bug

#195 [Issue-189] Load blogPosts component only when clicked <Anusha>
  src/components/navigation-bar/navigation-bar.jsx
  src/components/navigation-bar/navigation-bar.spec.jsx
  src/views/home/home.spec.jsx
Labels: blog, enhancement

#196 Fix #145 - Improve Lighthouse Accessibility
  src/components/card/card.jsx
  src/components/card/card.scss
  src/components/footer/footer.jsx
  src/components/header/header.jsx
  src/components/navigation-bar/navigation-bar.jsx
  src/components/slack-icon/slack-icon.jsx
  src/components/social-follow-links/social-follow-links.jsx
Labels: improvement
